Name: Human-Male
Species: 1
Parts:
- Name: SK_HUMN_BASE_01_01HEAD_HU01
  PartType: Head
  PartVersion: 1
- Name: SK_HUMN_BASE_01_02HAIR_HU01
  PartType: Hair
  PartVersion: 1
- Name: SK_HUMN_BASE_01_03EBRL_HU01
  PartType: EyebrowLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_04EBRR_HU01
  PartType: EyebrowRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_05EYEL_HU01
  PartType: EyeLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_06EYER_HU01
  PartType: EyeRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_07EARL_HU01
  PartType: EarLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_08EARR_HU01
  PartType: EarRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_35NOSE_HU01
  PartType: Nose
  PartVersion: 1
- Name: SK_HUMN_BASE_01_36TETH_HU01
  PartType: Teeth
  PartVersion: 1
- Name: SK_HUMN_BASE_01_37TONG_HU01
  PartType: Tongue
  PartVersion: 1
- Name: SK_HUMN_BASE_01_10TORS_HU01
  PartType: Torso
  PartVersion: 1
- Name: SK_HUMN_BASE_01_17HIPS_HU01
  PartType: Hips
  PartVersion: 1
- Name: SK_HUMN_BASE_01_11AUPL_HU01
  PartType: ArmUpperLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_12AUPR_HU01
  PartType: ArmUpperRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_13ALWL_HU01
  PartType: ArmLowerLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_14ALWR_HU01
  PartType: ArmLowerRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_15HNDL_HU01
  PartType: HandLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_16HNDR_HU01
  PartType: HandRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_21FOTR_HU01
  PartType: FootRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_20FOTL_HU01
  PartType: FootLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_19LEGR_HU01
  PartType: LegRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_18LEGL_HU01
  PartType: LegLeft
  PartVersion: 1
ColorSet:
  Species: 1
  Name: Default
  SourceColorPath: Assets\Synty\SidekickCharacters\Resources\Prefabs\Human-Female\Textures\T_Human-FemaleColorMap.png
  SourceMetallicPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_MetallicMap.png
  SourceSmoothnessPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_SmoothnessMap.png
  SourceReflectionPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_ReflectionMap.png
  SourceEmissionPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_EmissionMap.png
  SourceOpacityPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_OpacityMap.png
ColorRows: []
BlendShapes:
  BodyTypeValue: -100
