Name: Human-Female
Species: 1
Parts:
- Name: SK_HUMN_BASE_01_01HEAD_HU01
  PartType: Head
  PartVersion: 1
- Name: SK_HUMN_BASE_01_02HAIR_HU01
  PartType: Hair
  PartVersion: 1
- Name: SK_HUMN_BASE_01_03EBRL_HU01
  PartType: EyebrowLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_04EBRR_HU01
  PartType: EyebrowRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_05EYEL_HU01
  PartType: EyeLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_06EYER_HU01
  PartType: EyeRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_07EARL_HU01
  PartType: EarLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_08EARR_HU01
  PartType: EarRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_35NOSE_HU01
  PartType: Nose
  PartVersion: 1
- Name: SK_HUMN_BASE_01_36TETH_HU01
  PartType: Teeth
  PartVersion: 1
- Name: SK_HUMN_BASE_01_37TONG_HU01
  PartType: Tongue
  PartVersion: 1
- Name: SK_HUMN_BASE_01_10TORS_HU01
  PartType: Torso
  PartVersion: 1
- Name: SK_HUMN_BASE_01_17HIPS_HU01
  PartType: Hips
  PartVersion: 1
- Name: SK_HUMN_BASE_01_11AUPL_HU01
  PartType: ArmUpperLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_12AUPR_HU01
  PartType: ArmUpperRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_13ALWL_HU01
  PartType: ArmLowerLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_14ALWR_HU01
  PartType: ArmLowerRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_15HNDL_HU01
  PartType: HandLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_16HNDR_HU01
  PartType: HandRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_18LEGL_HU01
  PartType: LegLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_19LEGR_HU01
  PartType: LegRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_20FOTL_HU01
  PartType: FootLeft
  PartVersion: 1
- Name: SK_HUMN_BASE_01_21FOTR_HU01
  PartType: FootRight
  PartVersion: 1
- Name: SK_HUMN_BASE_01_38WRAP_HU01
  PartType: Wrap
  PartVersion: 1
ColorSet:
  Species: 1
  Name: Custom
  SourceColorPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_ColorMap.png
  SourceMetallicPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_MetallicMap.png
  SourceSmoothnessPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_SmoothnessMap.png
  SourceReflectionPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_ReflectionMap.png
  SourceEmissionPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_EmissionMap.png
  SourceOpacityPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_OpacityMap.png
ColorRows:
- ColorProperty: 1
  MainColor: EAB38B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 2
  MainColor: EAB38B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 3
  MainColor: EAB38B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 4
  MainColor: D09A78
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 5
  MainColor: EAB38B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 6
  MainColor: EAB38B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 7
  MainColor: EAB38B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 8
  MainColor: CD9C7D
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 9
  MainColor: CD9C7D
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 10
  MainColor: CD9C7D
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 11
  MainColor: CD9C7D
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 12
  MainColor: CD9C7D
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 13
  MainColor: CD9C7D
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 14
  MainColor: EAB38B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 15
  MainColor: E79A9C
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 16
  MainColor: FFF3CE
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 17
  MainColor: E5D8AF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 18
  MainColor: E79A9C
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 19
  MainColor: E79A9C
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 20
  MainColor: D0D0D0
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 21
  MainColor: D0D0D0
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 22
  MainColor: 6B4A27
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 23
  MainColor: 6B4A27
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 24
  MainColor: 262626
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 25
  MainColor: 262626
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 26
  MainColor: 8F6B46
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 27
  MainColor: 8F6B46
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 28
  MainColor: FFFFFF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 29
  MainColor: FFFFFF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 30
  MainColor: 6F5744
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 31
  MainColor: 6F5744
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 32
  MainColor: 6F5744
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 33
  MainColor: 6F5744
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 34
  MainColor: CAA58E
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 35
  MainColor: 6F5744
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 36
  MainColor: 6F5744
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 37
  MainColor: CAA58E
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 38
  MainColor: B35149
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 39
  MainColor: 944842
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 40
  MainColor: AFA382
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 41
  MainColor: 94896F
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
BlendShapes:
  BodyTypeValue: 100
