Name: ScifiRobots_01
Species: 8
Parts:
- Name: SK_ROBO_BASE_15_01HEAD_RO01
  PartType: Head
  PartVersion: 1
- Name: SK_SCFI_ROBO_03_10TORS_RO01
  PartType: Torso
  PartVersion: 1
- Name: SK_SCFI_ROBO_03_11AUPL_RO01
  PartType: ArmUpperLeft
  PartVersion: 1
- Name: SK_SCFI_ROBO_03_12AUPR_RO01
  PartType: ArmUpperRight
  PartVersion: 1
- Name: SK_SCFI_ROBO_06_13ALWL_RO01
  PartType: ArmLowerLeft
  PartVersion: 1
- Name: SK_SCFI_ROBO_06_14ALWR_RO01
  PartType: ArmLowerRight
  PartVersion: 1
- Name: SK_SCFI_ROBO_01_15HNDL_RO01
  PartType: HandLeft
  PartVersion: 1
- Name: SK_SCFI_ROBO_01_16HNDR_RO01
  PartType: HandRight
  PartVersion: 1
- Name: SK_SCFI_ROBO_03_17HIPS_RO01
  PartType: Hips
  PartVersion: 1
- Name: SK_SCFI_ROBO_02_18LEGL_RO01
  PartType: LegLeft
  PartVersion: 1
- Name: SK_SCFI_ROBO_02_19LEGR_RO01
  PartType: LegRight
  PartVersion: 1
- Name: SK_SCFI_ROBO_02_20FOTL_RO01
  PartType: FootLeft
  PartVersion: 1
- Name: SK_SCFI_ROBO_02_21FOTR_RO01
  PartType: FootRight
  PartVersion: 1
- Name: SK_SCFI_ROBO_02_24ABAC_RO01
  PartType: AttachmentBack
  PartVersion: 1
- Name: SK_SCFI_ROBO_03_29ASHL_RO01
  PartType: AttachmentShoulderLeft
  PartVersion: 1
- Name: SK_SCFI_ROBO_03_30ASHR_RO01
  PartType: AttachmentShoulderRight
  PartVersion: 1
ColorSet:
  Species: 8
  Name: Custom
  SourceColorPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_ColorMap.png
  SourceMetallicPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_MetallicMap.png
  SourceSmoothnessPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_SmoothnessMap.png
  SourceReflectionPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_ReflectionMap.png
  SourceEmissionPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_EmissionMap.png
  SourceOpacityPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_OpacityMap.png
ColorRows:
- ColorProperty: 1
  MainColor: F5C2A7
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 2
  MainColor: F5C2A7
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 3
  MainColor: F5C2A7
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 4
  MainColor: F5C2A7
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 5
  MainColor: E7B39D
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 6
  MainColor: F5C2A7
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 7
  MainColor: F5C2A7
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 8
  MainColor: F5C2A7
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 9
  MainColor: F5C2A7
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 10
  MainColor: D7A28B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 11
  MainColor: D7A28B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 12
  MainColor: D7A28B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 13
  MainColor: D7A28B
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 14
  MainColor: E7B39D
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 15
  MainColor: EA9999
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 16
  MainColor: FFF2CC
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 17
  MainColor: F0E3BB
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 18
  MainColor: EA9999
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 19
  MainColor: EA9999
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 20
  MainColor: AC4641
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 21
  MainColor: AC4641
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 22
  MainColor: 999999
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 23
  MainColor: 999999
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 24
  MainColor: 666666
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 25
  MainColor: 666666
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 26
  MainColor: 151515
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 27
  MainColor: 151515
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 28
  MainColor: FFFFFF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 29
  MainColor: FFFFFF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 30
  MainColor: 26272D
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 31
  MainColor: 26272D
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 32
  MainColor: 26272D
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 33
  MainColor: 26272D
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 34
  MainColor: B7B7B7
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 35
  MainColor: 26272D
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 36
  MainColor: 26272D
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 37
  MainColor: B7B7B7
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 38
  MainColor: FFFFFF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 39
  MainColor: FFFFFF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 40
  MainColor: 65615C
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 41
  MainColor: 65615C
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 42
  MainColor: 723C38
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 43
  MainColor: 784C3B
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 44
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 45
  MainColor: 7D6652
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 46
  MainColor: 6A5C4D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 47
  MainColor: 723C38
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 48
  MainColor: 2F3452
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 49
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 50
  MainColor: 7D6652
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 51
  MainColor: 6A5C4D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 52
  MainColor: 723C38
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 53
  MainColor: 2F3452
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 54
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 55
  MainColor: 7D6652
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 56
  MainColor: 6A5C4D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 57
  MainColor: 723C38
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 58
  MainColor: 2F3452
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 59
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 60
  MainColor: 7D6652
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 61
  MainColor: 6A5C4D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 62
  MainColor: 723C38
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 63
  MainColor: 2F3452
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 64
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 65
  MainColor: 7D6652
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 66
  MainColor: 6A5C4D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 67
  MainColor: 6D6D68
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 68
  MainColor: 6D5344
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 69
  MainColor: 723C38
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 70
  MainColor: 998B79
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 71
  MainColor: 52787F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 72
  MainColor: 6D6D68
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 73
  MainColor: 535660
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 74
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 75
  MainColor: 998B79
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 76
  MainColor: 52787F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 77
  MainColor: 6D6D68
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 78
  MainColor: 36373D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 79
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 80
  MainColor: 998B79
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 81
  MainColor: 52787F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 82
  MainColor: 69584A
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 83
  MainColor: 2F3452
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 84
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 85
  MainColor: 998B79
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 86
  MainColor: 51696D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 87
  MainColor: 69584A
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 88
  MainColor: 2F3452
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 89
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 90
  MainColor: 998B79
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 91
  MainColor: 51696D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 92
  MainColor: 7A593E
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 93
  MainColor: 7A593E
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 94
  MainColor: B7B7B7
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 95
  MainColor: 4C3A2D
  Metallic: B7B7B7
  Smoothness: B7B7B7
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 96
  MainColor: 282E3C
  Metallic: B7B7B7
  Smoothness: B7B7B7
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 97
  MainColor: 222221
  Metallic: B7B7B7
  Smoothness: B7B7B7
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 98
  MainColor: 72695E
  Metallic: B7B7B7
  Smoothness: B7B7B7
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 99
  MainColor: 2A2D31
  Metallic: B7B7B7
  Smoothness: B7B7B7
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 100
  MainColor: 4C3A2D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 101
  MainColor: 2D364C
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 102
  MainColor: 2A2928
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 103
  MainColor: 8D806F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 104
  MainColor: 32363D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 105
  MainColor: B51C00
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 106
  MainColor: 2D364C
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 107
  MainColor: 2A2928
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 108
  MainColor: 8D806F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 109
  MainColor: 32363D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 110
  MainColor: 2D3030
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 111
  MainColor: 998B79
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 112
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 113
  MainColor: 898580
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 114
  MainColor: 76726C
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 115
  MainColor: 2D3030
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 116
  MainColor: 918473
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 117
  MainColor: 504B45
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 118
  MainColor: 7D7973
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 119
  MainColor: 6A6660
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 120
  MainColor: 2D3030
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 121
  MainColor: 998B79
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 122
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 123
  MainColor: 898580
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 124
  MainColor: 76726C
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 125
  MainColor: 2D3030
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 126
  MainColor: 918473
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 127
  MainColor: 504B45
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 128
  MainColor: 7D7973
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 129
  MainColor: 6A6660
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 130
  MainColor: 2D3030
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 131
  MainColor: 998B79
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 132
  MainColor: 514C46
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 133
  MainColor: 898580
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 134
  MainColor: 76726C
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 135
  MainColor: 2D3030
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 136
  MainColor: 918473
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 137
  MainColor: 504B45
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 138
  MainColor: 7D7973
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 139
  MainColor: 6A6660
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 140
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 141
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 142
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 143
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 144
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 145
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 146
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 147
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 148
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 149
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 150
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 151
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 152
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 153
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 154
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 155
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 156
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 157
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 158
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 159
  MainColor: 383838
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 160
  MainColor: 929292
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: FFFFFF
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 161
  MainColor: 33405D
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: FFFFFF
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 162
  MainColor: 31343D
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: FFFFFF
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 163
  MainColor: 20222B
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: FFFFFF
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 164
  MainColor: B09D6E
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 165
  MainColor: B5904B
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 166
  MainColor: 8D569F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 167
  MainColor: 723F83
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 168
  MainColor: 6CB0C1
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: 000000
- ColorProperty: 169
  MainColor: 619978
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: 000000
- ColorProperty: 170
  MainColor: 00FFE4
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 171
  MainColor: 0074FF
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 172
  MainColor: 9A9FA2
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 173
  MainColor: 949AA2
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 174
  MainColor: 8D997D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 175
  MainColor: 838865
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 176
  MainColor: 2B2A27
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 177
  MainColor: 2B2926
  Metallic: FFFFFF
  Smoothness: FFFFFF
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 178
  MainColor: 8B8580
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 179
  MainColor: 5F6269
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 180
  MainColor: A0967F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 181
  MainColor: 897D63
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 182
  MainColor: 8B7B69
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 183
  MainColor: 746352
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 184
  MainColor: 785F49
  Metallic: AAAAAA
  Smoothness: AAAAAA
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 185
  MainColor: 695441
  Metallic: AAAAAA
  Smoothness: AAAAAA
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 186
  MainColor: 7A5F45
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 187
  MainColor: 614E3D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 188
  MainColor: B0946F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 189
  MainColor: 746451
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 190
  MainColor: 978874
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 191
  MainColor: 7F715F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 192
  MainColor: BDB7B0
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 193
  MainColor: A8A39F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 194
  MainColor: 7D6652
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 195
  MainColor: 8E7661
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 196
  MainColor: 954039
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 197
  MainColor: 6D403D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 198
  MainColor: 7B7879
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 199
  MainColor: 565656
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 200
  MainColor: FFFFFF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 201
  MainColor: FFFFFF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 202
  MainColor: FFFFFF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 203
  MainColor: FFFFFF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 204
  MainColor: FFFFFF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 205
  MainColor: FFFFFF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 206
  MainColor: FFFFFF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 207
  MainColor: FFFFFF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 208
  MainColor: FFFFFF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
- ColorProperty: 209
  MainColor: FFFFFF
  Metallic: FF0000
  Smoothness: FF0000
  Reflection: FF0000
  Emission: FF0000
  Opacity: FF0000
BlendShapes:
  BodyTypeValue: -100
  BodySizeValue: -41.9000015
  MuscleValue: 10.8000002
